//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MP3_Recorder.rc
//
#define IDC_ENTERCODE                   3
#define IDC_ORDER                       4
#define IDD_ABOUTBOX                    100
#define IDB_BTNREC                      101
#define IDD_MP3_REC_TEST_DIALOG         102
#define IDB_BTNPLAY                     102
#define IDB_BTNREW                      104
#define IDB_BTNFF                       105
#define IDB_BTNBEGIN                    106
#define IDB_BTNEND                      107
#define IDS_SLIDERTIME                  111
#define IDS_SLIDERVOL                   113
#define IDB_BTNVAS                      114
#define IDB_BTNFL                       115
#define IDW_STAT                        116
#define IDW_GRAPH                       117
#define IDW_TIME                        118
#define IDW_ICO                         119
#define IDB_BTNSTOP                     120
#define IDB_BTNOPEN                     121
#define IDB_BTNMIXR                     122
#define IDB_BTNMIX                      123
#define IDB_MIX_REC                     126
#define IDB_MIX_PLAY                    127
#define IDR_MAINFRAME                   128
#define IDB_MIX_INV                     128
#define IDD_NEW                         129
#define IDB_MIX_SEL                     129
#define IDS_RECLEVEL                    130
#define IDB_BTNMIX_EXCHANGE             130
#define IDS_VOLUME                      131
#define IDB_BTNMIX_SELECT               131
#define IDS_FILETITLE                   132
#define IDI_PLAY                        133
#define IDS_NOFILE                      133
#define IDD_COMMON                      134
#define IDS_FILEOPENTITLE               134
#define IDS_FILENEWTITLE                135
#define IDD_RECORD                      136
#define IDS_FILEFILTER                  136
#define IDS_FILENEWOPENTITLE            137
#define IDS_SEEKTO                      138
#define IDS_LOADING                     139
#define IDB_BMPREC                      140
#define IDS_DEL_NOFILE                  140
#define IDB_BMPSTOP                     141
#define IDS_DEL_UNABLE                  141
#define IDB_BMPPLAY                     142
#define IDS_DEL_ASK                     142
#define IDB_BMPPAUSE                    143
#define IDS_OPEN_ERR                    143
#define IDS_REC_NOSPACE                 145
#define IDS_DEC_INIT                    146
#define IDS_WAVEOUT_OPEN                147
#define IDS_WAVEOUT_START               148
#define IDI_STOP                        149
#define IDS_ENC_INIT                    149
#define IDS_ENC_ERR_DLL                 149
#define IDI_REC                         150
#define IDS_WAVEIN_OPEN                 150
#define IDI_OPEN                        151
#define IDS_WAVEIN_START                151
#define IDI_NEW                         152
#define IDS_CLEAR_ASK                   152
#define IDS_TT_OPEN                     153
#define IDI_DIN                         154
#define IDS_TT_REC                      154
#define IDS_TT_STOP                     155
#define IDS_TT_PLAY                     156
#define IDS_TT_MIXREC                   157
#define IDI_MIC                         158
#define IDS_TT_MIXPLAY                  158
#define IDS_TT_SEEKBAR                  159
#define IDS_TT_WAVEWND                  160
#define IDI_SEL                         161
#define IDS_TT_TIMEWND                  161
#define IDS_TT_STATWND                  162
#define IDR_MIXER_SELECT_MENU           163
#define IDS_REG_CAPTION                 163
#define IDI_LIN                         164
#define IDS_REG_TEXT_OK                 164
#define IDI_STM                         165
#define IDS_ENC_ERR_INIT                165
#define IDI_OTR                         166
#define IDS_VOLUME_TITLE                166
#define IDS_TT_VOLBAR                   167
#define IDS_TT_MIXSEL                   168
#define IDB_DIGITAL_WINDOW              169
#define IDS_TT_SCHEDULER                169
#define IDS_TT_VAS                      170
#define IDB_STAT_WND                    171
#define IDS_TT_MONITORING               171
#define IDB_TIME_WND                    172
#define IDB_STATBITMAPS                 177
#define IDB_TIMEBITMAPS                 178
#define IDI_MIXSEL                      179
#define IDI_PAUSE                       180
#define IDB_BITMAP1                     182
#define IDB_PROC_ICONS                  183
#define IDR_GRAPHMENU                   184
#define IDB_PEAKMETER                   185
#define IDI_DIN2                        187
#define IDI_MIC2                        188
#define IDB_GRAPH_WND                   191
#define IDR_STATMENU                    192
#define IDD_ENTERCODE                   193
#define IDC_HAND2                       194
#define IDR_MAINFRAME2                  195
#define IDD_NAGSCREEN                   198
#define IDR_TRAY_MENU                   201
#define IDI_TRAY_STOP                   202
#define IDI_TRAY_REC                    203
#define IDI_TRAY_PAUSE                  204
#define IDI_TRAY_PLAY                   205
#define IDD_FRAMEOWNER                  206
#define IDB_GWBG_LNP                    211
#define IDB_GWBG_LGP                    212
#define IDB_GWBG_DOTS                   213
#define IDB_GWBG_NONE                   216
#define IDB_GWPM_LN                     217
#define IDB_GWPM_LG                     218
#define IDD_AUTONAME                    219
#define IDT_MAINBAR                     221
#define IDR_MIXERBAR                    223
#define IDB_MAINBAR                     225
#define IDI_DOWNARROW                   226
#define IDD_SCHEDULER                   227
#define IDI_ICON1                       229
#define IDB_BTN_SCHED                   231
#define IDB_BTN_VAS                     232
#define IDB_BTN_MON                     238
#define IDD_VAS                         239
#define IDD_SCHEDULER2                  240
#define IDI_OPEN2                       243
#define IDD_TIMERDLG                    244
#define IDI_MIXLINE                     244
#define IDD__TESTDLG                    245
#define IDC_ARROW2                      245
#define IDI_MIXLINE00                   245
#define IDI_MIXLINE01                   246
#define IDI_MIXLINE02                   247
#define IDI_MIXLINE03                   248
#define IDI_MIXLINE04                   249
#define IDI_MIXLINE05                   250
#define IDI_MIXLINE06                   251
#define IDI_MIXLINE07                   252
#define IDI_MIXLINE08                   253
#define IDI_MIXLINE09                   254
#define IDI_MIXLINE10                   255
#define IDM_SOUND_REC                   300
#define IDM_SOUND_STOP                  301
#define IDM_SOUND_PLAY                  302
#define IDM_SOUND_BEGIN                 303
#define IDM_SOUND_REW                   304
#define IDM_SOUND_FF                    305
#define IDM_SOUND_END                   306
#define IDC_RECORD                      1000
#define IDC_STOP                        1001
#define IDC_RECBAR                      1002
#define IDC_RECQUALITY                  1003
#define IDR_OPT_OPEN                    1003
#define IDC_FILENAME                    1004
#define IDR_OPT_NEW                     1004
#define IDR_OPT_BLANK                   1005
#define IDC_TEST                        1006
#define IDC_FILENEW                     1008
#define IDC_AUTORUN                     1008
#define IDC_MINIMIZED                   1009
#define IDC_TRAYICON                    1010
#define IDC_TRAYMIN                     1011
#define IDC_RECDEVICE                   1012
#define IDC_SHOWTASKBAR                 1012
#define IDC_PLAYDEVICE                  1013
#define IDC_RECSOURCE                   1013
#define IDC_SLIDER1                     1016
#define IDC_VAS_TIME                    1017
#define IDC_MONO                        1018
#define IDC_STEREO                      1019
#define IDC_SAMPLEFREQ                  1021
#define IDC_11KHZ                       1022
#define IDC_22KHZ                       1023
#define IDC_44KHZ                       1024
#define IDC_AUTOFREQ                    1025
#define IDC_GROUP_FREQ                  1026
#define IDC_BITRATE_DESCR               1027
#define IDC_LIST1                       1039
#define IDC_TOOLTIP_ENABLE              1041
#define IDR_OPT_RELOAD                  1042
#define IDC_EDITCODE                    1042
#define IDC_REGNAME                     1043
#define IDC_GENERAL_SAVEPOS             1043
#define IDC_THANKSTO                    1044
#define IDC_PLAYERICON                  1045
#define IDC_PASTE                       1047
#define IDC_CLEAR                       1048
#define IDC_THANKYOU                    1049
#define IDC_BUTTON1                     1050
#define IDC_UNREGVERSION                1051
#define IDC_ONLINEREGISTER              1052
#define IDC_OPT_SHOWTASKBAR             1052
#define IDC_OPT_SHOWTRAY                1053
#define IDC_OPT_SHOWBOTH                1054
#define IDC_GETNOW                      1054
#define IDC_SH_ENABLE                   1061
#define IDC_SH_STARTH                   1062
#define IDE_NAMETEMPLATE                1063
#define IDC_SH_STOPH                    1063
#define IDC_SH_STARTM                   1064
#define IDE_NAMERESULT                  1065
#define IDC_SH_STOPM                    1065
#define IDC_SH_STARTS                   1066
#define IDC_SH_STOPS                    1067
#define IDC_SH_RECTIME                  1068
#define IDC_DATETIMEPICKER1             1070
#define IDC_SH_TPSTART                  1070
#define IDC_SH_TPSTOP                   1071
#define IDC_SH_TPRECTIME                1072
#define IDC_SH2_TPSTART                 1073
#define IDC_SH2_TPRECTIME               1074
#define IDC_AN_EXTEXT                   1075
#define IDC_SH2_TPSTOP                  1075
#define IDC_VAS_ENABLE                  1078
#define IDC_VAS_SILENTPAUSE             1081
#define IDC_VAS_SILENTSTOP              1082
#define IDC_VAS_THRESHOLD               1085
#define IDC_SH2_ENABLESTART             1087
#define IDC_SH2_BTN_STOPTIME            1088
#define IDC_SH2_BTN_RECTIME             1089
#define IDC_SH2_BTN_SHUTDOWN            1107
#define IDC_SH2_BTN_CLOSEALL            1108
#define IDC_SH2_RUNEXTERNAL             1111
#define IDC_SH2_ENABLESHR               1115
#define IDC_SH2_SELEXTERNAL             1116
#define IDC_SH2_STARTTEXT               1119
#define IDC_SH2_EDITFILENAME            1120
#define IDC_TDLG_ICON                   1126
#define IDC_TDLG_TEXT                   1127
#define IDC_STATIC2                     1133
#define IDC_STATIC3                     1134
#define IDC_STATIC4                     1135
#define IDC_STATIC5                     1136
#define IDC_STATIC0_1                   1141
#define IDC_STATIC1_1                   1142
#define IDC_STATIC0_0                   1143
#define IDC_STATIC1_0                   1144
#define IDC_STATIC2_1                   1145
#define IDC_STATIC3_1                   1146
#define IDC_STATIC2_0                   1147
#define IDC_STATIC3_0                   1148
#define IDC_STATIC4_0                   1149
#define IDC_STATIC5_0                   1150
#define IDC_STATIC6_0                   1151
#define IDC_STATIC7_0                   1152
#define IDC_STATIC8_0                   1153
#define IDC_STATIC9_0                   1154
#define IDC_STATIC4_1                   1155
#define IDC_STATIC5_1                   1156
#define IDC_STATIC6_1                   1157
#define IDC_STATIC7_1                   1158
#define IDC_STATIC8_1                   1159
#define IDC_STATIC9_1                   1160
#define IDC_AN_TDEFAULT                 1161
#define IDC_DLG_TRIALNOTE               1164
#define IDC_GEN_MINSTANCES              1165
#define IDC_STATIC_VERSION              1166
#define ID_MIXITEM_REC0                 3700
#define ID_MIXITEM_REC50                3750
#define ID_MIXITEM_PLAY0                3751
#define ID_MIXITEM_PLAY1                3752
#define IDM_FILE_NEW                    32773
#define IDM_FILE_OPEN                   32774
#define IDM_FILE_CREATEOPEN             32774
#define IDM_HELP_WWW                    32776
#define IDM_HELP_EMAIL                  32777
#define IDM_OPT_COM                     32779
#define IDA_SOUND_REC                   32815
#define IDA_SOUND_PLAY                  32816
#define IDM_OPT_TOP                     32827
#define IDM_MIX_PLAY                    32834
#define IDM_MIX_REC                     32835
#define ID_HELP_CONTENTS                32836
#define ID_HELP_KEYBOARDSHORTCUTS       32837
#define IDM_FILE_CLOSE                  32839
#define IDM_FILE_FINDTARGET             32840
#define IDM_FILE_FINDFILE               32840
#define IDM_OPT_EM                      32842
#define IDM_HELP_DOC                    32845
#define IDM_HELP_GETFULL                32846
#define ID_TEST1_MICROPHONE             32852
#define ID_TEST1_LINEIN                 32853
#define ID_TEST1_STEREOMIX              32854
#define ID_TEST1_VOLUME                 32855
#define ID_TEST1_OTHER                  32857
#define ID_GRAPH_PEAKMETER              32866
#define ID_GRAPH_PEAKMETERDB            32867
#define ID_GRAPH_OSCILLOSCOPE           32868
#define IDM_FILE_DELETE                 32869
#define ID_GRAPH_NONE                   32869
#define IDM_FILE_CLEAR                  32871
#define ID_STAT_PREF                    32873
#define IDM_OPT_SNDDEV                  32874
#define ID_HELP_HOWTO                   32875
#define ID_HELP_ENTERREGISTRATIONCODE   32876
#define ID_HELP_ENTERCODE               32876
#define IDA_HELP_DOC                    32877
#define ID__SHOW                        32878
#define IDM_TRAY_SHOW                   32878
#define ID__REC_CTRL                    32879
#define ID__VOL_CTRL                    32880
#define ID__REC                         32884
#define IDM_TRAY_REC                    32884
#define ID__STOP                        32885
#define IDM_TRAY_STOP                   32885
#define ID__PLAY                        32886
#define IDM_TRAY_PLAY                   32886
#define ID__EXIT                        32887
#define IDM_TRAY_EXIT                   32887
#define ID__PREF                        32889
#define ID__TOP                         32890
#define ID__MOVE                        32891
#define IDM_TRAY_ABOUT                  32895
#define ID_HELP_ORDERONLINE             32901
#define IDT_BTNMIXREC                   32906
#define IDT_BTNMIXPLAY                  32907
#define IDA_VOL_UP                      32908
#define IDA_VOL_DOWN                    32909
#define ID_GRAPH_MAXPEAKS               32917

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        247
#define _APS_NEXT_COMMAND_VALUE         32918
#define _APS_NEXT_CONTROL_VALUE         1167
#define _APS_NEXT_SYMED_VALUE           132
#endif
#endif
