//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MP3_Recorder.rc
//
#define IDC_ENTERCODE                   3
#define IDC_ORDER                       4
#define IDD_ABOUTBOX                    100
#define IDB_BTNREC                      101
#define IDB_BTNPLAY                     102
#define IDS_SLIDERTIME                  111
#define IDS_SLIDERVOL                   113
#define IDW_STAT                        116
#define IDW_GRAPH                       117
#define IDW_TIME                        118
#define IDW_ICO                         119
#define IDW_RECORDING_ITEM              5000
#define IDB_BTNSTOP                     120
#define IDB_BTNOPEN                     121
#define IDB_MIX_REC                     126
#define IDB_MIX_PLAY                    127
#define IDR_MAINFRAME                   128
#define IDB_MIX_SEL                     129
#define IDS_ERROR_DIRECTORY             129
#define IDS_FILETITLE                   132
#define IDI_PLAY                        133
#define IDS_NOFILE                      133
#define IDD_COMMON                      134
#define IDS_FILEOPENTITLE               134
#define IDS_FILENEWTITLE                135
#define IDD_RECORD                      136
#define IDS_FILEFILTER                  136
#define IDS_FILENEWOPENTITLE            137
#define IDS_SEEKTO                      138
#define IDS_DEL_UNABLE                  141
#define IDS_DEL_ASK                     142
#define IDI_STOP                        149
#define IDI_REC                         150
#define IDI_OPEN                        151
#define IDI_NEW                         152
#define IDS_CLEAR_ASK                   152
#define IDS_TT_OPEN                     153
#define IDS_TT_REC                      154
#define IDS_TT_STOP                     155
#define IDS_TT_PLAY                     156
#define IDS_TT_MIXREC                   157
#define IDI_MIC                         158
#define IDS_TT_MIXPLAY                  158
#define IDS_TT_SEEKBAR                  159
#define IDS_TT_WAVEWND                  160
#define IDS_TT_TIMEWND                  161
#define IDS_TT_STATWND                  162
#define IDS_REG_CAPTION                 163
#define IDS_REG_TEXT_OK                 164
#define IDS_VOLUME_TITLE                166
#define IDS_TT_VOLBAR                   167
#define IDS_TT_MIXSEL                   168
#define IDS_TT_SCHEDULER                169
#define IDS_TT_VAS                      170
#define IDB_STAT_WND                    171
#define IDS_TT_MONITORING               171
#define IDB_TIME_WND                    172
#define IDB_STATBITMAPS                 177
#define IDB_TIMEBITMAPS                 178
#define IDI_PAUSE                       180
#define IDB_PROC_ICONS                  183
#define IDR_GRAPHMENU                   184
#define IDR_STATMENU                    192
#define IDD_ENTERCODE                   193
#define IDC_HAND2                       194
#define IDR_MAINFRAME2                  195
#define IDD_NAGSCREEN                   198
#define IDR_TRAY_MENU                   201
#define IDI_TRAY_STOP                   202
#define IDI_TRAY_REC                    203
#define IDI_TRAY_PAUSE                  204
#define IDI_TRAY_PLAY                   205
#define IDB_GWBG_LNP                    211
#define IDB_GWBG_LGP                    212
#define IDB_GWBG_DOTS                   213
#define IDB_GWBG_NONE                   216
#define IDB_GWPM_LN                     217
#define IDB_GWPM_LG                     218
#define IDD_AUTONAME                    219
#define IDB_BTN_SCHED                   231
#define IDB_BTN_VAS                     232
#define IDB_BTN_MON                     238
#define IDD_VAS                         239
#define IDD_SCHEDULER2                  240
#define IDI_OPEN2                       243
#define IDD_TIMERDLG                    244
#define IDI_MIXLINE                     244
#define IDI_MIXLINE00                   245
#define IDI_MIXLINE01                   246
#define IDI_MIXLINE02                   247
#define IDD_RECORDING_SOURCE            247
#define IDI_MIXLINE03                   248
#define IDI_MIXLINE04                   249
#define IDI_MIXLINE05                   250
#define IDI_MIXLINE06                   251
#define IDI_MIXLINE07                   252
#define IDI_MIXLINE08                   253
#define IDI_MIXLINE09                   254
#define IDI_MIXLINE10                   255
#define IDM_SOUND_REC                   300
#define IDM_SOUND_STOP                  301
#define IDM_SOUND_PLAY                  302
#define IDM_SOUND_BEGIN                 303
#define IDM_SOUND_REW                   304
#define IDM_SOUND_FF                    305
#define IDM_SOUND_END                   306
#define IDR_OPT_NEW                     1004
#define IDR_OPT_BLANK                   1005
#define IDC_AUTORUN                     1008
#define IDC_MINIMIZED                   1009
#define IDC_TRAYICON                    1010
#define IDC_TRAYMIN                     1011
#define IDC_RECDEVICE                   1012
#define IDC_SLIDER1                     1016
#define IDC_VAS_TIME                    1017
#define IDC_MONO                        1018
#define IDC_STEREO                      1019
#define IDC_SAMPLEFREQ                  1021
#define IDC_11KHZ                       1022
#define IDC_22KHZ                       1023
#define IDC_44KHZ                       1024
#define IDC_AUTOFREQ                    1025
#define IDC_GROUP_FREQ                  1026
#define IDC_BITRATE_DESCR               1027
#define IDC_TOOLTIP_ENABLE              1041
#define IDR_OPT_RELOAD                  1042
#define IDC_EDITCODE                    1042
#define IDC_REGNAME                     1043
#define IDC_THANKSTO                    1044
#define IDC_PLAYERICON                  1045
#define IDC_PASTE                       1047
#define IDC_CLEAR                       1048
#define IDC_THANKYOU                    1049
#define IDC_BUTTON1                     1050
#define IDC_UNREGVERSION                1051
#define IDC_ONLINEREGISTER              1052
#define IDC_GETNOW                      1054
#define IDE_NAMETEMPLATE                1063
#define IDC_SH2_TPSTART                 1073
#define IDC_SH2_TPRECTIME               1074
#define IDC_AN_EXTEXT                   1075
#define IDC_SH2_TPSTOP                  1075
#define IDC_VAS_ENABLE                  1078
#define IDC_VAS_SILENTPAUSE             1081
#define IDC_VAS_SILENTSTOP              1082
#define IDC_VAS_THRESHOLD               1085
#define IDC_SH2_ENABLESTART             1087
#define IDC_SH2_BTN_STOPTIME            1088
#define IDC_SH2_BTN_RECTIME             1089
#define IDC_SH2_BTN_SHUTDOWN            1107
#define IDC_SH2_BTN_CLOSEALL            1108
#define IDC_SH2_RUNEXTERNAL             1111
#define IDC_SH2_ENABLESHR               1115
#define IDC_SH2_SELEXTERNAL             1116
#define IDC_SH2_STARTTEXT               1119
#define IDC_SH2_EDITFILENAME            1120
#define IDC_TDLG_ICON                   1126
#define IDC_TDLG_TEXT                   1127
#define IDC_STATIC0_1                   1141
#define IDC_STATIC1_1                   1142
#define IDC_STATIC0_0                   1143
#define IDC_STATIC1_0                   1144
#define IDC_STATIC2_1                   1145
#define IDC_STATIC3_1                   1146
#define IDC_STATIC2_0                   1147
#define IDC_STATIC3_0                   1148
#define IDC_STATIC4_0                   1149
#define IDC_STATIC5_0                   1150
#define IDC_STATIC6_0                   1151
#define IDC_STATIC7_0                   1152
#define IDC_STATIC8_0                   1153
#define IDC_STATIC9_0                   1154
#define IDC_STATIC4_1                   1155
#define IDC_STATIC5_1                   1156
#define IDC_STATIC6_1                   1157
#define IDC_STATIC7_1                   1158
#define IDC_STATIC8_1                   1159
#define IDC_STATIC9_1                   1160
#define IDC_AN_TDEFAULT                 1161
#define IDC_DLG_TRIALNOTE               1164
#define IDC_GEN_MINSTANCES              1165
#define IDC_STATIC_VERSION              1166
#define IDC_PLAYBACK_DEVICE             1167
#define IDC_RECORDING_DEVICE            1168
#define IDC_DEVICES_LIST                1175
#define ID_MIXITEM_LOOPBACK_DEVICE      3688
#define ID_MIXITEM_PLAY_VOLUME          3697
#define ID_MIXITEM_REC_LOOPBACK         3698
#define ID_MIXITEM_REC_LOOPBACK_MIX     3699
#define ID_MIXITEM_REC0                 3700
#define ID_MIXITEM_REC50                3750
#define ID_MIXITEM_PLAY0                3751
#define ID_MIXITEM_PLAY1                3752
#define IDM_FILE_NEW                    32773
#define IDM_FILE_OPEN                   32774
#define IDM_FILE_CREATEOPEN             32774
#define IDM_HELP_WWW                    32776
#define IDM_HELP_EMAIL                  32777
#define IDM_OPT_COM                     32779
#define IDA_SOUND_REC                   32815
#define IDA_SOUND_PLAY                  32816
#define IDM_OPT_TOP                     32827
#define IDM_MIX_PLAY                    32834
#define IDM_MIX_REC                     32835
#define IDM_FILE_CLOSE                  32839
#define IDM_FILE_FINDTARGET             32840
#define IDM_FILE_FINDFILE               32840
#define IDM_OPT_EM                      32842
#define IDM_HELP_DOC                    32845
#define IDM_HELP_GETFULL                32846
#define ID_GRAPH_PEAKMETER              32865
#define ID_GRAPH_PEAKMETERDB            32866
#define ID_GRAPH_OSCILLOSCOPE           32867
#define ID_GRAPH_NONE                   32868
#define IDM_FILE_DELETE                 32870
#define IDM_FILE_CLEAR                  32871
#define ID_STAT_PREF                    32873
#define IDM_OPT_SNDDEV                  32874
#define ID_HELP_HOWTO                   32875
#define ID_HELP_ENTERREGISTRATIONCODE   32876
#define ID_HELP_ENTERCODE               32876
#define IDA_HELP_DOC                    32877
#define IDM_TRAY_SHOW                   32878
#define IDM_TRAY_REC                    32884
#define IDM_TRAY_STOP                   32885
#define IDM_TRAY_PLAY                   32886
#define IDM_TRAY_EXIT                   32887
#define IDM_TRAY_ABOUT                  32895
#define ID_HELP_ORDERONLINE             32901
#define IDA_VOL_UP                      32908
#define IDA_VOL_DOWN                    32909
#define ID_GRAPH_MONITORING             32923
#define ID_OPTIONS_SELECTSOUCE          32924
#define ID_OPTIONS_SELECTRECORDINGSOUCE 32925
#define ID_OPTIONS_SELECTRECORDINGSOURCE 32926

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        248
#define _APS_NEXT_COMMAND_VALUE         32927
#define _APS_NEXT_CONTROL_VALUE         1176
#define _APS_NEXT_SYMED_VALUE           132
#endif
#endif
